name: CI

on:
  push:
    branches: ['master', 'main']

  pull_request:
    branches: ['master', 'main', 'dev', 'develop']

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies, Lint and Tests
      run: |
        make init-actions

  build-on-mac:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies, Lint and Tests
      run: |
        make init-actions

    - name: Pytest
      run: |
        make pytest

  build-on-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies, Lint
      run: |
        make init-actions

    - name: Pytest
      run: |
        make pytest
